const colorTheme = {
  pink: {
    bg: "bg-pink-200",
    hover: "hover:bg-pink-300",
    focus: "focus:outline-pink-600",
    buttonBg: "bg-pink-600",
    buttonHover: "hover:bg-pink-500",
    buttonFocus: "focus:outline-pink-600",
    buttonText: "text-white",
    linkText: "text-pink-600 hover:text-pink-500",
    text: "text-pink-600",
    textDark: "text-pink-800",
    textLight: "text-pink-500",
    border: "border-pink-800",
    borderLight: "border-pink-400",
    icon: "text-pink-600",
    hoverText: "hover:text-pink-900",
  },
  indigo: {
    bg: "bg-indigo-200",
    hover: "hover:bg-indigo-300",
    focus: "focus:outline-indigo-600",
    buttonBg: "bg-indigo-600",
    buttonHover: "hover:bg-indigo-500",
    buttonFocus: "focus:outline-indigo-600",
    buttonText: "text-white",
    linkText: "text-indigo-600 hover:text-indigo-500",
    text: "text-indigo-600",
    textDark: "text-indigo-800",
    textLight: "text-indigo-500",
    border: "border-indigo-800",
    borderLight: "border-indigo-400",
    icon: "text-indigo-600",
    hoverText: "hover:text-indigo-900",
  },
  rose: {
    bg: "bg-rose-200",
    hover: "hover:bg-rose-300",
    focus: "focus:outline-rose-600",
    buttonBg: "bg-rose-600",
    buttonHover: "hover:bg-rose-500",
    buttonFocus: "focus:outline-rose-600",
    buttonText: "text-white",
    linkText: "text-rose-600 hover:text-rose-500",
    text: "text-rose-600",
    textDark: "text-rose-800",
    textLight: "text-rose-500",
    border: "border-rose-800",
    borderLight: "border-rose-400",
    icon: "text-rose-600",
    hoverText: "hover:text-rose-900",
  },
  violet: {
    bg: "bg-violet-200",
    hover: "hover:bg-violet-300",
    focus: "focus:outline-violet-600",
    buttonBg: "bg-violet-600",
    buttonHover: "hover:bg-violet-500",
    buttonFocus: "focus:outline-violet-600",
    buttonText: "text-white",
    linkText: "text-violet-600 hover:text-violet-500",
    text: "text-violet-600",
    textDark: "text-violet-800",
    textLight: "text-violet-500",
    border: "border-violet-800",
    borderLight: "border-violet-400",
    icon: "text-violet-600",
    hoverText: "hover:text-violet-900",
  },
  blue: {
    bg: "bg-blue-200",
    hover: "hover:bg-blue-300",
    focus: "focus:outline-blue-600",
    buttonBg: "bg-blue-600",
    buttonHover: "hover:bg-blue-500",
    buttonFocus: "focus:outline-blue-600",
    buttonText: "text-white",
    linkText: "text-blue-600 hover:text-blue-500",
    text: "text-blue-600",
    textDark: "text-blue-800",
    textLight: "text-blue-500",
    border: "border-blue-800",
    borderLight: "border-blue-400",
    icon: "text-blue-600",
    hoverText: "hover:text-blue-900",
  },
  red: {
    bg: "bg-red-200",
    hover: "hover:bg-red-300",
    focus: "focus:outline-red-600",
    buttonBg: "bg-red-600",
    buttonHover: "hover:bg-red-500",
    buttonFocus: "focus:outline-red-600",
    buttonText: "text-white",
    linkText: "text-red-600 hover:text-red-500",
    text: "text-red-600",
    textDark: "text-red-800",
    textLight: "text-red-500",
    border: "border-red-800",
    borderLight: "border-red-400",
    icon: "text-red-600",
    hoverText: "hover:text-red-900",
  },
  orange: {
    bg: "bg-orange-200",
    hover: "hover:bg-orange-300",
    focus: "focus:outline-orange-600",
    buttonBg: "bg-orange-600",
    buttonHover: "hover:bg-orange-500",
    buttonFocus: "focus:outline-orange-600",
    buttonText: "text-white",
    linkText: "text-orange-600 hover:text-orange-500",
    text: "text-orange-600",
    textDark: "text-orange-800",
    textLight: "text-orange-500",
    border: "border-orange-800",
    borderLight: "border-orange-400",
    icon: "text-orange-600",
    hoverText: "hover:text-orange-900",
  },
  purple: {
    bg: "bg-purple-200",
    hover: "hover:bg-purple-300",
    focus: "focus:outline-purple-600",
    buttonBg: "bg-purple-600",
    buttonHover: "hover:bg-purple-500",
    buttonFocus: "focus:outline-purple-600",
    buttonText: "text-white",
    linkText: "text-purple-600 hover:text-purple-500",
    text: "text-purple-600",
    textDark: "text-purple-800",
    textLight: "text-purple-500",
    border: "border-purple-800",
    borderLight: "border-purple-400",
    icon: "text-purple-600",
    hoverText: "hover:text-purple-900",
  },
  emerald: {
    bg: "bg-emerald-200",
    hover: "hover:bg-emerald-300",
    focus: "focus:outline-emerald-600",
    buttonBg: "bg-emerald-600",
    buttonHover: "hover:bg-emerald-500",
    buttonFocus: "focus:outline-emerald-600",
    buttonText: "text-white",
    linkText: "text-emerald-600 hover:text-emerald-500",
    text: "text-emerald-600",
    textDark: "text-emerald-800",
    textLight: "text-emerald-500",
    border: "border-emerald-800",
    borderLight: "border-emerald-400",
    icon: "text-emerald-600",
    hoverText: "hover:text-emerald-900",
  },
  sky: {
    bg: "bg-sky-200",
    hover: "hover:bg-sky-300",
    focus: "focus:outline-sky-600",
    buttonBg: "bg-sky-600",
    buttonHover: "hover:bg-sky-500",
    buttonFocus: "focus:outline-sky-600",
    buttonText: "text-white",
    linkText: "text-sky-600 hover:text-sky-500",
    text: "text-sky-600",
    textDark: "text-sky-800",
    textLight: "text-sky-500",
    border: "border-sky-800",
    borderLight: "border-sky-400",
    icon: "text-sky-600",
    hoverText: "hover:text-sky-900",
  },
  green: {
    bg: "bg-green-200",
    hover: "hover:bg-green-300",
    focus: "focus:outline-green-600",
    buttonBg: "bg-green-600",
    buttonHover: "hover:bg-green-500",
    buttonFocus: "focus:outline-green-600",
    buttonText: "text-white",
    linkText: "text-green-600 hover:text-green-500",
    text: "text-green-600",
    textDark: "text-green-800",
    textLight: "text-green-500",
    border: "border-green-800",
    borderLight: "border-green-400",
    icon: "text-green-600",
    hoverText: "hover:text-green-900",
  },
  yellow: {
    bg: "bg-yellow-200",
    hover: "hover:bg-yellow-300",
    focus: "focus:outline-yellow-600",
    buttonBg: "bg-yellow-600",
    buttonHover: "hover:bg-yellow-500",
    buttonFocus: "focus:outline-yellow-600",
    buttonText: "text-white",
    linkText: "text-yellow-600 hover:text-yellow-500",
    text: "text-yellow-600",
    textDark: "text-yellow-800",
    textLight: "text-yellow-500",
    border: "border-yellow-800",
    borderLight: "border-yellow-400",
    icon: "text-yellow-600",
    hoverText: "hover:text-yellow-900",
  },
  gray: {
    bg: "bg-gray-200",
    hover: "hover:bg-gray-300",
    focus: "focus:outline-gray-600",
    buttonBg: "bg-gray-600",
    buttonHover: "hover:bg-gray-500",
    buttonFocus: "focus:outline-gray-600",
    buttonText: "text-white",
    linkText: "text-gray-600 hover:text-gray-500",
    text: "text-gray-600",
    textDark: "text-gray-800",
    textLight: "text-gray-500",
    border: "border-gray-800",
    borderLight: "border-gray-400",
    icon: "text-gray-600",
    hoverText: "hover:text-gray-900",
  },
  fuchsia: {
    bg: "bg-fuchsia-200",
    hover: "hover:bg-fuchsia-300",
    focus: "focus:outline-fuchsia-600",
    buttonBg: "bg-fuchsia-600",
    buttonHover: "hover:bg-fuchsia-500",
    buttonFocus: "focus:outline-fuchsia-600",
    buttonText: "text-white",
    linkText: "text-fuchsia-600 hover:text-fuchsia-500",
    text: "text-fuchsia-600",
    textDark: "text-fuchsia-800",
    textLight: "text-fuchsia-500",
    border: "border-fuchsia-800",
    borderLight: "border-fuchsia-400",
    icon: "text-fuchsia-600",
    hoverText: "hover:text-fuchsia-900",
  },
  teal: {
    bg: "bg-teal-200",
    hover: "hover:bg-teal-300",
    focus: "focus:outline-teal-600",
    buttonBg: "bg-teal-600",
    buttonHover: "hover:bg-teal-500",
    buttonFocus: "focus:outline-teal-600",
    buttonText: "text-white",
    linkText: "text-teal-600 hover:text-teal-500",
    text: "text-teal-600",
    textDark: "text-teal-800",
    textLight: "text-teal-500",
    border: "border-teal-800",
    borderLight: "border-teal-400",
    icon: "text-teal-600",
    hoverText: "hover:text-teal-900",
  },
};

export default colorTheme;
